"""aumentando tamanho dos campos codigo_ibge e cep

Revision ID: 735c3482f1b4
Revises: 880010eaf32f
Create Date: 2025-02-15 13:04:22.407927

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '735c3482f1b4'
down_revision = '880010eaf32f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('escolas', schema=None) as batch_op:
        batch_op.alter_column('cep',
               existing_type=mysql.VARCHAR(length=8),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.alter_column('codigo_ibge',
               existing_type=mysql.VARCHAR(length=7),
               type_=sa.String(length=10),
               existing_nullable=True)

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('codigo_ibge',
               existing_type=mysql.VARCHAR(length=7),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.alter_column('cep',
               existing_type=mysql.VARCHAR(length=8),
               type_=sa.String(length=10),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('cep',
               existing_type=sa.String(length=10),
               type_=mysql.VARCHAR(length=8),
               existing_nullable=True)
        batch_op.alter_column('codigo_ibge',
               existing_type=sa.String(length=10),
               type_=mysql.VARCHAR(length=7),
               existing_nullable=True)

    with op.batch_alter_table('escolas', schema=None) as batch_op:
        batch_op.alter_column('codigo_ibge',
               existing_type=sa.String(length=10),
               type_=mysql.VARCHAR(length=7),
               existing_nullable=True)
        batch_op.alter_column('cep',
               existing_type=sa.String(length=10),
               type_=mysql.VARCHAR(length=8),
               existing_nullable=True)

    # ### end Alembic commands ###
