"""criando todas as tabelas

Revision ID: 880010eaf32f
Revises: 
Create Date: 2025-02-15 12:57:21.637446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '880010eaf32f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_ibge', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('estado', sa.String(length=2), nullable=False),
    sa.Column('codigo_inep', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_ibge')
    )
    op.create_table('disciplinas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('escolas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_de_registro', sa.String(length=2), nullable=False),
    sa.Column('codigo_inep', sa.String(length=8), nullable=True),
    sa.Column('nome_da_escola', sa.String(length=200), nullable=True),
    sa.Column('cep', sa.String(length=8), nullable=True),
    sa.Column('codigo_ibge', sa.String(length=7), nullable=True),
    sa.Column('endereco', sa.String(length=200), nullable=True),
    sa.Column('numero', sa.String(length=10), nullable=True),
    sa.Column('complemento', sa.String(length=100), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=True),
    sa.Column('ddd', sa.String(length=2), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('telefone_2', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('ensino_fundamental', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Ano_escolar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipos_ensino',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('tipos_usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('banco_questoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('questao', sa.Text(), nullable=False),
    sa.Column('alternativa_a', sa.Text(), nullable=False),
    sa.Column('alternativa_b', sa.Text(), nullable=False),
    sa.Column('alternativa_c', sa.Text(), nullable=False),
    sa.Column('alternativa_d', sa.Text(), nullable=False),
    sa.Column('alternativa_e', sa.Text(), nullable=True),
    sa.Column('questao_correta', sa.String(length=1), nullable=False),
    sa.Column('disciplina_id', sa.Integer(), nullable=False),
    sa.Column('assunto', sa.Text(), nullable=False),
    sa.Column('ano_escolar_id', sa.Integer(), nullable=True),
    sa.Column('mes_id', sa.Integer(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['disciplina_id'], ['disciplinas.id'], ),
    sa.ForeignKeyConstraint(['mes_id'], ['meses.id'], ),
    sa.ForeignKeyConstraint(['ano_escolar_id'], ['Ano_escolar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('escola_tipos_ensino',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('escola_id', sa.Integer(), nullable=False),
    sa.Column('tipo_ensino_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['escola_id'], ['escolas.id'], ),
    sa.ForeignKeyConstraint(['tipo_ensino_id'], ['tipos_ensino.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('simulados_gerados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ano_escolar_id', sa.Integer(), nullable=False),
    sa.Column('mes_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('data_envio', sa.DateTime(), nullable=True),
    sa.Column('disciplina_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['disciplina_id'], ['disciplinas.id'], ),
    sa.ForeignKeyConstraint(['mes_id'], ['meses.id'], ),
    sa.ForeignKeyConstraint(['ano_escolar_id'], ['Ano_escolar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('turmas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_de_registro', sa.String(length=2), nullable=False),
    sa.Column('codigo_inep', sa.String(length=8), nullable=False),
    sa.Column('escola_id', sa.Integer(), nullable=False),
    sa.Column('tipo_ensino_id', sa.Integer(), nullable=False),
    sa.Column('ano_escolar_id', sa.Integer(), nullable=False),
    sa.Column('turma', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['escola_id'], ['escolas.id'], ),
    sa.ForeignKeyConstraint(['ano_escolar_id'], ['Ano_escolar.id'], ),
    sa.ForeignKeyConstraint(['tipo_ensino_id'], ['tipos_ensino.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('simulado_questoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simulado_id', sa.Integer(), nullable=False),
    sa.Column('questao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['questao_id'], ['banco_questoes.id'], ),
    sa.ForeignKeyConstraint(['simulado_id'], ['simulados_gerados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_registro', sa.String(length=2), nullable=False),
    sa.Column('codigo_inep_escola', sa.String(length=8), nullable=True),
    sa.Column('cpf', sa.String(length=11), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('senha', sa.String(length=255), nullable=True),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('data_nascimento', sa.String(length=10), nullable=True),
    sa.Column('mae', sa.String(length=200), nullable=True),
    sa.Column('pai', sa.String(length=200), nullable=True),
    sa.Column('sexo', sa.Integer(), nullable=True),
    sa.Column('codigo_ibge', sa.String(length=7), nullable=True),
    sa.Column('cep', sa.String(length=8), nullable=True),
    sa.Column('escola_id', sa.Integer(), nullable=True),
    sa.Column('tipo_ensino_id', sa.Integer(), nullable=True),
    sa.Column('ano_escolar_id', sa.Integer(), nullable=True),
    sa.Column('turma_id', sa.Integer(), nullable=True),
    sa.Column('tipo_usuario_id', sa.Integer(), nullable=False),
    sa.Column('cidade_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cidade_id'], ['cidades.id'], ),
    sa.ForeignKeyConstraint(['escola_id'], ['escolas.id'], ),
    sa.ForeignKeyConstraint(['ano_escolar_id'], ['Ano_escolar.id'], ),
    sa.ForeignKeyConstraint(['tipo_ensino_id'], ['tipos_ensino.id'], ),
    sa.ForeignKeyConstraint(['tipo_usuario_id'], ['tipos_usuarios.id'], ),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assuntos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('disciplina_id', sa.Integer(), nullable=False),
    sa.Column('ano_escolar_id', sa.Integer(), nullable=False),
    sa.Column('professor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['disciplina_id'], ['disciplinas.id'], ),
    sa.ForeignKeyConstraint(['professor_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['ano_escolar_id'], ['Ano_escolar.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome', 'disciplina_id', 'ano_escolar_id', 'professor_id')
    )
    op.create_table('professor_turma_escola',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('professor_id', sa.Integer(), nullable=False),
    sa.Column('escola_id', sa.Integer(), nullable=False),
    sa.Column('turma_id', sa.Integer(), nullable=False),
    sa.Column('tipo_ensino_id', sa.Integer(), nullable=False),
    sa.Column('ano_escolar_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['escola_id'], ['escolas.id'], ),
    sa.ForeignKeyConstraint(['professor_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['ano_escolar_id'], ['Ano_escolar.id'], ),
    sa.ForeignKeyConstraint(['tipo_ensino_id'], ['tipos_ensino.id'], ),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('simulados_gerados_professor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('professor_id', sa.Integer(), nullable=False),
    sa.Column('disciplina_id', sa.Integer(), nullable=False),
    sa.Column('ano_escolar_id', sa.Integer(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('mes_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['disciplina_id'], ['disciplinas.id'], ),
    sa.ForeignKeyConstraint(['mes_id'], ['meses.id'], ),
    sa.ForeignKeyConstraint(['professor_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['ano_escolar_id'], ['Ano_escolar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('simulado_questoes_professor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simulado_id', sa.Integer(), nullable=False),
    sa.Column('questao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['questao_id'], ['banco_questoes.id'], ),
    sa.ForeignKeyConstraint(['simulado_id'], ['simulados_gerados_professor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('simulados_enviados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simulado_id', sa.Integer(), nullable=False),
    sa.Column('turma_id', sa.Integer(), nullable=False),
    sa.Column('data_envio', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('data_limite', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['simulado_id'], ['simulados_gerados_professor.id'], ),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aluno_simulado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('simulado_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('data_resposta', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['simulado_id'], ['simulados_enviados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('desempenho_simulado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('simulado_id', sa.Integer(), nullable=False),
    sa.Column('escola_id', sa.Integer(), nullable=False),
    sa.Column('ano_escolar_id', sa.Integer(), nullable=False),
    sa.Column('codigo_ibge', sa.Integer(), nullable=False),
    sa.Column('respostas_aluno', sa.JSON(), nullable=False),
    sa.Column('respostas_corretas', sa.JSON(), nullable=False),
    sa.Column('desempenho', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('data_resposta', sa.DateTime(), nullable=True),
    sa.Column('tipo_usuario_id', sa.Integer(), nullable=False),
    sa.Column('turma_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['escola_id'], ['escolas.id'], ),
    sa.ForeignKeyConstraint(['ano_escolar_id'], ['Ano_escolar.id'], ),
    sa.ForeignKeyConstraint(['simulado_id'], ['simulados_enviados.id'], ),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('desempenho_simulado')
    op.drop_table('aluno_simulado')
    op.drop_table('simulados_enviados')
    op.drop_table('simulado_questoes_professor')
    op.drop_table('simulados_gerados_professor')
    op.drop_table('professor_turma_escola')
    op.drop_table('assuntos')
    op.drop_table('usuarios')
    op.drop_table('simulado_questoes')
    op.drop_table('turmas')
    op.drop_table('simulados_gerados')
    op.drop_table('escola_tipos_ensino')
    op.drop_table('banco_questoes')
    op.drop_table('tipos_usuarios')
    op.drop_table('tipos_ensino')
    op.drop_table('Ano_escolar')
    op.drop_table('meses')
    op.drop_table('escolas')
    op.drop_table('disciplinas')
    op.drop_table('cidades')
    # ### end Alembic commands ###
