"""permitindo questao_id nulo em simulado_questoes

Revision ID: 91266115a385
Revises: 735c3482f1b4
Create Date: 2025-02-15 13:25:24.076682

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '91266115a385'
down_revision = '735c3482f1b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simulado_questoes', schema=None) as batch_op:
        batch_op.alter_column('questao_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simulado_questoes', schema=None) as batch_op:
        batch_op.alter_column('questao_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
